### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by xXxCryxXx** [bri3d/VW_Flash#40]
Hello, is there any install info? On my Lapto does it work without any issue but on the Desktop PC it dose not work ... everytime i try to start the window close it as soon as it opens 

pip install -r requirements.txt was done ..

if i try to open the tool via command line it is missing the Moduls see below:

dashing module not loaded
Traceback (most recent call last):
  File "VW_Flash_GUI.py", line 870, in <module>
  File "VW_Flash_GUI.py", line 601, in __init__
  File "VW_Flash_GUI.py", line 156, in __init__
  File "VW_Flash_GUI.py", line 121, in poll_interfaces
  File "VW_Flash_GUI.py", line 106, in get_dlls_from_registry
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden
[15256] Failed to execute script 'VW_Flash_GUI' due to unhandled exception!

i got Python 3.9

**Comment by bri3d** [comment]
No more information about _what_ unhandled exception? The rest of these errors are somewhat expected - the FileNotFoundError is because you don't have a Registry entry for a J2534 device. Dashing not being available is not an issue. So there is something else unexpected wrong here I think.

On Windows you should almost always use the premade release from https://github.com/bri3d/VW_Flash/releases/ anyway.
